[book]
title = "BeetstreamNext"
description = "Fully-featured music server for Beets.io music libraries implementing the OpenSubsonic API"
authors = ["FlorentLM"]
language = "en"
src = "src"

[output.html]
default-theme = "light"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/FlorentLM/BeetstreamNext"
edit-url-template = "https://github.com/FlorentLM/BeetstreamNext/edit/main/docs/{path}"
additional-css = ["theme/custom.css"]
additional-js = ["js/mermaid.min.js", "js/mermaid-init.js"]

[output.html.search]
enable = true
limit-results = 20

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
